name: Build and Release .deb

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install fpm dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build Go binary
        run: |
          go build -o picovpnd ./daemon/main.go

      - name: Build .deb package
        run: |
          fpm -s dir -t deb -n picovpnd -v "${GITHUB_REF_NAME#v}" ./picovpnd=/usr/bin/picovpnd

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: picovpnd_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}